service: nnssa

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.7
  lambdaHashingVersion: 20201221
  region: eu-west-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:PutObject"
            - "states:StartExecution"
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:CreateNetworkInterface"
            - "ec2:DeleteNetworkInterface"
            - "ec2:DescribeInstances"
            - "ec2:AttachNetworkInterface"
          Resource: "*"

functions:
  transform:
    timeout: 30
    memorySize: 2048
    handler: src/services/transform.transform
    environment: ${self:custom.env}
    vpc: ${self:custom.vpc}
    layers:
      - arn:aws:lambda:eu-west-1:785963298336:layer:libsndfilePython37:1
      - arn:aws:lambda:eu-west-1:785963298336:layer:ffmpegPython37:1
  predict:
    timeout: 30
    handler: src/services/predict.predict
    environment: ${self:custom.env}
    vpc: ${self:custom.vpc}
  post:
    timeout: 30
    handler: src/services/post.post
    environment: ${self:custom.env}
    vpc: ${self:custom.vpc}
  error:
    environment: ${self:custom.env}
    handler: src/api/error.error
  success:
    environment: ${self:custom.env}
    handler: src/api/success.success
  start:
    runtime: nodejs12.x
    events:
      - s3:
          bucket: nnssa-songs
          event: s3:ObjectCreated:*
          rules:
            - prefix: songs/
          existing: true
    environment:
      statemachine_arn: ${self:resources.Outputs.PredictionPipeline.Value}
    handler: src/api/start.start
  upload:
    runtime: nodejs12.x
    events:
      - http:
          method: post
          path: upload
          cors: true
    handler: src/api/upload.upload
  notify:
    timeout: 30
    runtime: nodejs12.x
    handler: src/api/notify.notify
    environment: ${self:custom.env}

package:
  exclude:
    - node_modules/**
    - venv/**
    - .vscode/**
    - .serverless/**
    - .pytest_cache/**
    - __pychache__/**
    - secrets.*.yml

custom:
  bucketName: nnssa-songs
  efsAccessPoint: arn:aws:elasticfilesystem:eu-west-1:785963298336:access-point/fsap-065b8c81f6ce7a91f
  localMountPath: /mnt/access
  subnetsId: subnet-a7091cc1
  securityGroup: sg-03b82e00393071834
  vpc:
    securityGroupIds:
      - ${self:custom.securityGroup}
    subnetIds:
      - ${self:custom.subnetsId}
  notifyLambda: arn:aws:lambda:eu-west-1:785963298336:function:nnssa-dev-notify
  secrets: ${file(secrets.${self:provider.stage}.yml)}
  env:
    MQTT_HOST: ${self:custom.secrets.MQTT_HOST}
    MQTT_PORT: ${self:custom.secrets.MQTT_PORT}
    MQTT_USERNAME: ${self:custom.secrets.MQTT_USERNAME}
    MQTT_PASSWORD: ${self:custom.secrets.MQTT_PASSWORD}

stepFunctions:
  validate: true
  stateMachines:
    predictionPipeline:
      name: predictionPipeline
      definition: ${file(./steps.yml)}
      loggingConfig:
        level: ERROR
        includeExecutionData: true
        destinations:
          - arn:aws:logs:eu-west-1:785963298336:log-group:statemachine:*

resources:
  Outputs:
    PredictionPipeline:
      Description: The prediction pipeline statemachine
      Value:
        Ref: PredictionPipeline
  extensions:
    TransformLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: "${self:custom.efsAccessPoint}"
            LocalMountPath: "${self:custom.localMountPath}"
    PredictLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: "${self:custom.efsAccessPoint}"
            LocalMountPath: "${self:custom.localMountPath}"
    PostLambdaFunction:
      Properties:
        FileSystemConfigs:
          - Arn: "${self:custom.efsAccessPoint}"
            LocalMountPath: "${self:custom.localMountPath}"

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-secrets-plugin
